// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNHSNKo-lWchJibzaPPBkNEJYv3x1mch4',
    appId: '1:906825621823:web:bea084bafde9af03bb338a',
    messagingSenderId: '906825621823',
    projectId: 'parchooniwalaa',
    authDomain: 'parchooniwalaa.firebaseapp.com',
    storageBucket: 'parchooniwalaa.appspot.com',
    measurementId: 'G-SD1BJWTQRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqrv3_BuXWx3gYMCVGOuUchTJYLmVZoxA',
    appId: '1:906825621823:android:3cdb2c7cd85e5013bb338a',
    messagingSenderId: '906825621823',
    projectId: 'parchooniwalaa',
    storageBucket: 'parchooniwalaa.appspot.com',
  );
}
